version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_setup_my_jenkins_files:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    command: bash -c "mkdir -p /tmp/download && \
                       curl -L https://download.docker.com/linux/static/stable/x86_64/docker-18.03.1-ce.tgz | tar -xz -C /tmp/download && \
                       rm -rf /tmp/download/docker/dockerd && \
                       mv /tmp/download/docker/docker* /usr/local/bin/ && \
                       rm -rf /tmp/download && \
                       groupadd -g 999 docker && \
                       usermod -aG staff,docker jenkins && \
                       su-exec jenkins /usr/local/bin/jenkins.sh"

volumes:
  jenkins_home:

