version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - my_jenkins_files:/var/jenkins_home

volumes:
  my_jenkins_files:

